apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  type: ClusterIP  # or NodePort if you want external access
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: php-app
