apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: <your-docker-hub-username>/php-app:latest  # Replace with your PHP app image
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "mysql"  # Service name of the MySQL database
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"  # MySQL username
            - name: DB_PASSWORD
              value: "rootpassword"  # MySQL password
            - name: DB_NAME
              value: "visitor_management"  # MySQL database name
